samples: "samples.tsv"
units: "units.tsv"

reference:
  fasta: ""

threads:
  - 1

tools:
  bamutil: "docker://marrip/bamutil:v1.0.14"
  bwamem2: "docker://marrip/bwa-mem2:2.2.1"
  common: "docker://marrip/common:1.1.0"
  r: "docker://marrip/r-base:4.0.3"
