$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  threads:
    type: object
  tools:
    type: object
    properties:
      common:
        type: string
      bwamem2:
        type: string
  required:
    - samples
    - units
    - threads
    - tools
